name: Build and Test Docker Image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  test_and_build:
    strategy:
      matrix:
        scheme: [small, full]
    name: Build LaTeX-Docker with MySTjs [${{ matrix.scheme }}-scheme]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      SCHEME: ${{ matrix.scheme }}
    steps:
      - name: Set up Git
        uses: actions/checkout@v3
      - name: Build
        run: |
          docker build -t texlive-$SCHEME-mystjs --build-arg scheme=$SCHEME .
      - name: Test
        run: |
          docker run --rm -v $(pwd)/tests:/tests texlive-$SCHEME-mystjs /bin/sh -c "/tests/install_deps.sh && myst build /tests/test.md --yes"
          file $(pwd)/tests/exports/test.pdf
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        if: "github.ref == 'refs/heads/main' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')"
        # login should've been done by the action
        run: |
          TAG="ghcr.io/kai-tub/texlive-$SCHEME-mystjs"
          VERSION="$(date "+%Y%m%d")"
          docker tag texlive-$SCHEME-mystjs $TAG:$VERSION
          docker tag texlive-$SCHEME-mystjs $TAG:latest
          docker images $TAG
          docker push $TAG:$VERSION
          docker push $TAG:latest
